#!/bin/sh

filename=$(date +%Y%m%d%H%M%S)
CurrentPath=$(pwd)

user=$(bin/rconfig src/config/sequelize.json production.username)
password=$(bin/rconfig src/config/sequelize.json production.password)
database=$(bin/rconfig src/config/sequelize.json production.database)

mysqldump -u$user -p$password $database | gzip > $CurrentPath/backup/$filename.gz